server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true